image: python:3.8

stages:
  - test
  - docs
  - deploy

before_script:
  - pip install -U pip
  - pip install pipenv
  - pipenv install --dev

include:
  - local: .gitlab/ci/lint.gitlab-ci.yml
  - local: .gitlab/ci/test.gitlab-ci.yml
  - local: .gitlab/ci/docs.gitlab-ci.yml
