# hifis-surveyval
# Framework to help developing analysis scripts for the HIFIS Software survey.
#
# SPDX-FileCopyrightText: 2021 HIFIS Software <support@hifis.net>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

test:
  before_script:
    - pip install -U pip
    - pip install poetry
    - poetry config virtualenvs.in-project true
    - poetry install
  stage: test
  script:
    - make test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - ".gitlab/ci/test.gitlab-ci.yml"
        - "hifis_surveyval/**/*"
        - "tests/**/*"
        - ".gitlab-ci.yml"
        - "Makefile"
        - "poetry.lock"
        - "pyproject.toml"

check_links:
    stage: test
    image: ruby:2.7.2-slim-buster
    before_script:
        - gem install awesome_bot
    script:
        - awesome_bot --allow-redirect --allow-dupe `find . -name "*.md"`
        - awesome_bot --allow-redirect --allow-dupe `find . -name "*.rst"`
    rules:
      - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
        changes:
          - "**/*.md"
          - "**/*.rst"
          - ".gitlab/ci/test.gitlab-ci.yml"
          - ".gitlab-ci.yml"
